# Generated by Django 6.1.1 on 2026-09-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('id_rotas', models.AutoField(primary_key=True, serialize=False)),
                ('rota', models.TextField(max_length=255)),
                ('motorista', models.TextField(max_length=255)),
            ],
        ),
    ]
